### ISSUE TITLE
it crashes after a while

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/changes-demo#8]
after few loops or randomly moving the cursor, some times a white screen appears.

**Comment by sebastianovide** [comment]
testing fix in https://github.com/Geovation/changes-demo/pull/7

**Comment by kdalkafoukis** [comment]
Mapbox 0.46 seems to solve the problem + enhancements like prevent the video from infinite looping or stop the video when the browser window is not visible - #10 a7dbf29

**Comment by sebastianovide** [comment]
the CPU is overloaded when a new frame is trigger before the previous one has been rendered
