### ISSUE TITLE
try cesium instead of mapboxgl

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/changes-demo#9]
example: https://3d.taipei/apps/4DCMap.html

as mapbox gl doesn't seem mature enough for 4D, we'll search luck in Cesium.

**Comment by kdalkafoukis** [comment]
After extended research and implementations I regard that Cesium doesn't provide an open-source tool to create 3d-tiles the equivalent of vector tiles that provide the performance needed for a heavy dataset like the demo's.The open-source community hasn't created a tool as well.FME is a platform that was used to create the 3d-tiles but it doesn't create tiles for different zoom levels and the tile size is bigger than 100mb for 2d version and 500mb for the 3d version (per frame) which makes the it a bad solution for our needs.
